name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run tests
        run: pytest .
      - name: Run lint
        run: flake8 .